[versions]
project = "1.0.0"
kotlin = "1.9.10"
agp = "8.1.0"
jvmTarget = "18"

android-minSdk = "26"
android-compileSdk = "34"
android-targetSdk = "34"

compose-jetbrains = "1.5.10-rc02"
androidx-activityCompose = "1.8.0"

# Decompose
decompose = "2.2.0-alpha02"
essenty = "1.3.0-alpha01"

# Project Dependencies
jsoup = "1.16.1"
koin = "3.5.0"
datastore-preferences = "1.1.0-alpha05"
okhttp = "4.11.0"
kamelImage = "0.7.3"
commons-text = "1.10.0"
kotlinx-coroutines-core-jvm = "1.7.3"
kotlinx-serialization-json = "1.6.0"
libres = "1.2.0-beta01"
realm = "1.11.1"
ktxCore = "1.12.0"
koinCompose = "1.1.0"
ktor-ktorClientOkhttp = "2.3.4"
datastore = "1.1.0-alpha05"
materialKolor = "1.2.6"
versions-plugin = "0.49.0"
composeColorPickerJvm = "0.7.0"
composeColorPicker = "0.7.0"
multiplatform-settings = "1.1.0"

[libraries]
androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }

compose-color-picker-android = { module = "com.godaddy.android.colorpicker:compose-color-picker-android", version.ref = "composeColorPickerJvm" }
compose-color-picker-jvm = { module = "com.godaddy.android.colorpicker:compose-color-picker-jvm", version.ref = "composeColorPickerJvm" }
compose-color-picker = { module = "com.godaddy.android.colorpicker:compose-color-picker", version.ref = "composeColorPicker" }
decompose-decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensionsComposeJetbrains = { group = "com.arkivanov.decompose", name = "extensions-compose-jetbrains", version.ref = "decompose" }

essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }

androidx-core = { module = "androidx.core:core", version.ref = "ktxCore" }

koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
ktor-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-ktorClientOkhttp" }
libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
libres-plugin = { module = "io.github.skeptick.libres:gradle-plugin", version.ref = "libres" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamelImage" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatform-settings" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
realm-library-base = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines-core-jvm" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

[plugins]
libres = { id = "io.github.skeptick.libres", version.ref = "libres" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-jetbrains" }
realm-plugin = { id = "io.realm.kotlin", version.ref = "realm" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }